kind: PersistentVolume
apiVersion: v1
metadata:
  name: homepage-postgres-pv-volume
  labels:
    app: postgres
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/homepage-volume/data"